### ISSUE TITLE
Failed to transact error | White blank screen on phone

### ISSUE THREAD

**Issue by vashisth00** [khalithartmann/flutter_arcore_plugin#11]
##Error

 E/flutter (29057): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter (29057): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter (29057): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (29057): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter (29057): #4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429:36)
E/flutter (29057): #5      SystemChrome.setPreferredOrientations (package:flutter/src/services/system_chrome.dart:236:35)
E/flutter (29057): #6      main (package:arcore_plugin_example/main.dart:9:16)
E/flutter (29057): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (29057): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (29057): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (29057): #10     _runZoned (dart:async/zone.dart:1518:10)
E/flutter (29057): #11     runZoned (dart:async/zone.dart:1502:12)
E/flutter (29057): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (29057): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (29057): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (29057): 
E/flutter (29057): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (29057): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (29057): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (29057): #0      main.<anonymous closure> (package:arcore_plugin_example/main.dart:25:5)
E/flutter (29057): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (29057): #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (29057): #3      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
E/flutter (29057): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
E/flutter (29057): #5      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
E/flutter (29057): #6      Future._completeError (dart:async/future_impl.dart:532:5)
E/flutter (29057): #7      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
E/flutter (29057): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (29057): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (29057): #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (29057): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (29057): #12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (29057): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter (29057): 
E/BpSurfaceComposerClient(29057): Failed to transact (-1)
E/BpSurfaceComposerClient(29057): Failed to transact (-1)
W/ViewRootImpl[MainActivity](29057): Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=513.52454, y[0]=1904.0083, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=25505225, downTime=25505186, deviceId=8, source=0x1002 }
I/chatty  (29057): uid=10392(com.peqas.arcorepluginexample) identical 1 line
W/ViewRootImpl[MainActivity](29057): Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=513.52454, y[0]=1904.0083, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=25505225, downTime=25505186, deviceId=8, source=0x1002 }
E/BpSurfaceComposerClient(29057): Failed to transact (-1)
E/BpSurfaceComposerClient(29057): Failed to transact (-1)
I/zygote  (29057): Do partial code cache collection, code=23KB, data=30KB
I/zygote  (29057): After code cache collection, code=23KB, data=30KB
I/zygote  (29057): Increasing code cache capacity to 128KB

**Comment by msndvlpr** [comment]
Adding the line `WidgetsFlutterBinding.ensureInitialized();` at the first line of `main()` method solved my problem but only in the example project not in my own source code- while having the same code, I don't know why.

**Comment by khal-it** [comment]
could you describe your problem and add some example code @msndvlpr

**Comment by khal-it** [comment]
there is a new version could you check it and give me feedback ? @msndvlpr @vashisth00

**Comment by vashisth00** [comment]
I figured it, resolved after the new update
