### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by murilinhoPs** [khalithartmann/flutter_arcore_plugin#4]
Hi,
It's not a problem/issue, I just wanted to know if you could explain to me de example code becausr I wanted to know how place a 3d model that I made into my room to test arcore. And I didn't find anything explaining how to do this, could you help me please?

**Comment by tonmoy054** [comment]
Maybe you can get some idea from here:

https://medium.com/@difrancescogianmarco/arcore-flutter-plugin-add-object-on-the-plane-8b3d7cbde3d3

https://youtu.be/Gf-Qu29RLUo
